import "dotenv/config";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { listingsTable, personasTable } from "./schema";

const sql = neon(process.env.DIRECT_URL!);
const db = drizzle(sql);

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(personasTable);
  await db.delete(listingsTable);

  // --- LISTINGS ---
  await db.insert(listingsTable).values([
    // FOR SALE listings
    {
      listingType: "forSale",
      status: "active",
      homeType: "single-family",
      salePrice: "485000.00",
      monthlyRent: null,
      streetAddress: "742 Evergreen Terrace",
      city: "Austin",
      state: "TX",
      zip: "78701",
      bedrooms: 4,
      bathrooms: "2.5",
      sqft: 2400,
      garageSize: 2,
      allowedPets: null,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/742-evergreen-1.jpg", "/images/742-evergreen-2.jpg"],
      yearBuilt: 2018,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "A",
      walkScore: 72,
      transitScore: 55,
      bikeScore: 68,
      hoa: true,
      hoaFee: "150.00",
      amenities: ["central-ac", "hardwood-floors", "fenced-yard", "smart-home"],
    },
    {
      listingType: "forSale",
      status: "active",
      homeType: "condo",
      salePrice: "320000.00",
      monthlyRent: null,
      streetAddress: "1200 Congress Ave Unit 405",
      city: "Austin",
      state: "TX",
      zip: "78701",
      bedrooms: 2,
      bathrooms: "2.0",
      sqft: 1100,
      garageSize: 1,
      allowedPets: null,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/1200-congress-1.jpg"],
      yearBuilt: 2021,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "A",
      walkScore: 95,
      transitScore: 88,
      bikeScore: 90,
      hoa: true,
      hoaFee: "425.00",
      amenities: ["pool", "gym", "rooftop-deck", "concierge", "central-ac"],
    },
    {
      listingType: "forSale",
      status: "active",
      homeType: "single-family",
      salePrice: "275000.00",
      monthlyRent: null,
      streetAddress: "3421 Bluebonnet Lane",
      city: "Round Rock",
      state: "TX",
      zip: "78664",
      bedrooms: 3,
      bathrooms: "2.0",
      sqft: 1800,
      garageSize: 2,
      allowedPets: null,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/3421-bluebonnet-1.jpg", "/images/3421-bluebonnet-2.jpg"],
      yearBuilt: 2005,
      schoolDistrictName: "Round Rock ISD",
      schoolDistrictRating: "A",
      walkScore: 42,
      transitScore: 25,
      bikeScore: 38,
      hoa: true,
      hoaFee: "85.00",
      amenities: ["fenced-yard", "community-pool", "playground"],
    },
    {
      listingType: "forSale",
      status: "active",
      homeType: "townhouse",
      salePrice: "389000.00",
      monthlyRent: null,
      streetAddress: "88 Mueller Blvd",
      city: "Austin",
      state: "TX",
      zip: "78723",
      bedrooms: 3,
      bathrooms: "2.5",
      sqft: 1650,
      garageSize: 1,
      allowedPets: null,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/88-mueller-1.jpg"],
      yearBuilt: 2020,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "B",
      walkScore: 82,
      transitScore: 65,
      bikeScore: 78,
      hoa: true,
      hoaFee: "200.00",
      amenities: ["central-ac", "energy-efficient", "community-garden"],
    },
    {
      listingType: "forSale",
      status: "under-contract",
      homeType: "single-family",
      salePrice: "625000.00",
      monthlyRent: null,
      streetAddress: "15 Westlake Drive",
      city: "Austin",
      state: "TX",
      zip: "78746",
      bedrooms: 5,
      bathrooms: "3.5",
      sqft: 3200,
      garageSize: 3,
      allowedPets: null,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/15-westlake-1.jpg", "/images/15-westlake-2.jpg", "/images/15-westlake-3.jpg"],
      yearBuilt: 2015,
      schoolDistrictName: "Eanes ISD",
      schoolDistrictRating: "A",
      walkScore: 28,
      transitScore: 15,
      bikeScore: 35,
      hoa: false,
      hoaFee: null,
      amenities: ["pool", "outdoor-kitchen", "home-theater", "wine-cellar", "fenced-yard"],
    },
    {
      listingType: "forSale",
      status: "active",
      homeType: "multi-family",
      salePrice: "550000.00",
      monthlyRent: null,
      streetAddress: "2200 East Riverside Dr",
      city: "Austin",
      state: "TX",
      zip: "78741",
      bedrooms: 4,
      bathrooms: "3.0",
      sqft: 2800,
      garageSize: 0,
      allowedPets: null,
      allowedPetType: null,
      hasImages: false,
      images: null,
      yearBuilt: 1985,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "C",
      walkScore: 68,
      transitScore: 72,
      bikeScore: 60,
      hoa: false,
      hoaFee: null,
      amenities: ["duplex", "rental-income-potential"],
    },

    // FOR RENT listings
    {
      listingType: "forRent",
      status: "available",
      homeType: "apartment",
      salePrice: null,
      monthlyRent: "1850.00",
      streetAddress: "500 East 4th St Apt 312",
      city: "Austin",
      state: "TX",
      zip: "78701",
      bedrooms: 1,
      bathrooms: "1.0",
      sqft: 750,
      garageSize: 0,
      allowedPets: true,
      allowedPetType: "cat",
      hasImages: true,
      images: ["/images/500-e4th-1.jpg"],
      yearBuilt: 2019,
      schoolDistrictName: null,
      schoolDistrictRating: null,
      walkScore: 97,
      transitScore: 92,
      bikeScore: 88,
      hoa: false,
      hoaFee: null,
      amenities: ["pool", "gym", "dog-park", "package-lockers", "central-ac"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "apartment",
      salePrice: null,
      monthlyRent: "2400.00",
      streetAddress: "222 West Ave Unit 1801",
      city: "Austin",
      state: "TX",
      zip: "78701",
      bedrooms: 2,
      bathrooms: "2.0",
      sqft: 1050,
      garageSize: 1,
      allowedPets: true,
      allowedPetType: "all",
      hasImages: true,
      images: ["/images/222-west-1.jpg", "/images/222-west-2.jpg"],
      yearBuilt: 2022,
      schoolDistrictName: null,
      schoolDistrictRating: null,
      walkScore: 94,
      transitScore: 85,
      bikeScore: 82,
      hoa: false,
      hoaFee: null,
      amenities: ["pool", "gym", "rooftop-deck", "ev-charging", "central-ac", "in-unit-laundry"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "single-family",
      salePrice: null,
      monthlyRent: "2800.00",
      streetAddress: "1405 Pease Rd",
      city: "Austin",
      state: "TX",
      zip: "78703",
      bedrooms: 3,
      bathrooms: "2.0",
      sqft: 1600,
      garageSize: 1,
      allowedPets: true,
      allowedPetType: "all",
      hasImages: true,
      images: ["/images/1405-pease-1.jpg", "/images/1405-pease-2.jpg"],
      yearBuilt: 1962,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "A",
      walkScore: 78,
      transitScore: 60,
      bikeScore: 72,
      hoa: false,
      hoaFee: null,
      amenities: ["fenced-yard", "hardwood-floors", "washer-dryer", "central-ac"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "townhouse",
      salePrice: null,
      monthlyRent: "2200.00",
      streetAddress: "6700 Burnet Rd Unit 14",
      city: "Austin",
      state: "TX",
      zip: "78757",
      bedrooms: 2,
      bathrooms: "1.5",
      sqft: 1200,
      garageSize: 1,
      allowedPets: false,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/6700-burnet-1.jpg"],
      yearBuilt: 2010,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "B",
      walkScore: 70,
      transitScore: 58,
      bikeScore: 65,
      hoa: true,
      hoaFee: "175.00",
      amenities: ["community-pool", "central-ac", "in-unit-laundry"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "single-family",
      salePrice: null,
      monthlyRent: "3500.00",
      streetAddress: "901 Canyon Edge Dr",
      city: "Austin",
      state: "TX",
      zip: "78733",
      bedrooms: 4,
      bathrooms: "3.0",
      sqft: 2600,
      garageSize: 2,
      allowedPets: true,
      allowedPetType: "dog",
      hasImages: true,
      images: ["/images/901-canyon-1.jpg", "/images/901-canyon-2.jpg", "/images/901-canyon-3.jpg"],
      yearBuilt: 2008,
      schoolDistrictName: "Eanes ISD",
      schoolDistrictRating: "A",
      walkScore: 22,
      transitScore: 10,
      bikeScore: 30,
      hoa: true,
      hoaFee: "120.00",
      amenities: ["pool", "fenced-yard", "outdoor-kitchen", "central-ac", "smart-home"],
    },
    {
      listingType: "forRent",
      status: "unavailable",
      homeType: "apartment",
      salePrice: null,
      monthlyRent: "1450.00",
      streetAddress: "4500 S Lamar Blvd Apt 208",
      city: "Austin",
      state: "TX",
      zip: "78745",
      bedrooms: 1,
      bathrooms: "1.0",
      sqft: 680,
      garageSize: 0,
      allowedPets: true,
      allowedPetType: "cat",
      hasImages: false,
      images: null,
      yearBuilt: 1998,
      schoolDistrictName: null,
      schoolDistrictRating: null,
      walkScore: 65,
      transitScore: 52,
      bikeScore: 55,
      hoa: false,
      hoaFee: null,
      amenities: ["pool", "laundry-room"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "condo",
      salePrice: null,
      monthlyRent: "1950.00",
      streetAddress: "300 Bowie St Unit 2204",
      city: "Austin",
      state: "TX",
      zip: "78703",
      bedrooms: 2,
      bathrooms: "2.0",
      sqft: 980,
      garageSize: 1,
      allowedPets: true,
      allowedPetType: "all",
      hasImages: true,
      images: ["/images/300-bowie-1.jpg", "/images/300-bowie-2.jpg"],
      yearBuilt: 2017,
      schoolDistrictName: "Austin ISD",
      schoolDistrictRating: "B",
      walkScore: 91,
      transitScore: 80,
      bikeScore: 75,
      hoa: false,
      hoaFee: null,
      amenities: ["pool", "gym", "concierge", "central-ac", "balcony"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "apartment",
      salePrice: null,
      monthlyRent: "1250.00",
      streetAddress: "8100 Shoal Creek Blvd Apt 105",
      city: "Austin",
      state: "TX",
      zip: "78757",
      bedrooms: 1,
      bathrooms: "1.0",
      sqft: 620,
      garageSize: 0,
      allowedPets: false,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/8100-shoal-1.jpg"],
      yearBuilt: 1990,
      schoolDistrictName: null,
      schoolDistrictRating: null,
      walkScore: 60,
      transitScore: 45,
      bikeScore: 55,
      hoa: false,
      hoaFee: null,
      amenities: ["laundry-room", "covered-parking"],
    },
    // Out of state listings for variety
    {
      listingType: "forSale",
      status: "active",
      homeType: "single-family",
      salePrice: "350000.00",
      monthlyRent: null,
      streetAddress: "2847 Magnolia St",
      city: "Denver",
      state: "CO",
      zip: "80207",
      bedrooms: 3,
      bathrooms: "2.0",
      sqft: 1450,
      garageSize: 1,
      allowedPets: null,
      allowedPetType: null,
      hasImages: true,
      images: ["/images/2847-magnolia-1.jpg"],
      yearBuilt: 1955,
      schoolDistrictName: "Denver Public Schools",
      schoolDistrictRating: "B",
      walkScore: 80,
      transitScore: 62,
      bikeScore: 88,
      hoa: false,
      hoaFee: null,
      amenities: ["hardwood-floors", "updated-kitchen", "fenced-yard"],
    },
    {
      listingType: "forRent",
      status: "available",
      homeType: "apartment",
      salePrice: null,
      monthlyRent: "1700.00",
      streetAddress: "1600 Pearl St Apt 402",
      city: "Denver",
      state: "CO",
      zip: "80203",
      bedrooms: 1,
      bathrooms: "1.0",
      sqft: 800,
      garageSize: 0,
      allowedPets: true,
      allowedPetType: "all",
      hasImages: true,
      images: ["/images/1600-pearl-1.jpg"],
      yearBuilt: 2020,
      schoolDistrictName: null,
      schoolDistrictRating: null,
      walkScore: 92,
      transitScore: 78,
      bikeScore: 95,
      hoa: false,
      hoaFee: null,
      amenities: ["gym", "rooftop-deck", "bike-storage", "ev-charging", "central-ac"],
    },
  ]);

  // --- PERSONAS ---
  await db.insert(personasTable).values([
    // Persona A: Single buyer/renter
    {
      role: "buyer",
      name: "Alex Chen",
      income: 95000,
      budget: 350000,
      hasKids: false,
      hasPets: true,
      petType: "cat",
      preferredCity: ["Austin"],
      preferredState: ["TX"],
    },
    // Persona B: Family with kids + pets
    {
      role: "renter",
      name: "Maria & James Rodriguez",
      income: 145000,
      budget: 3200,
      hasKids: true,
      hasPets: true,
      petType: "dog",
      preferredCity: ["Austin", "Round Rock"],
      preferredState: ["TX"],
    },
  ]);

  console.log("Seeding complete!");
  console.log("  - 16 listings inserted");
  console.log("  - 2 personas inserted");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
